stages:
 - build
 - push-build

build:
 stage: build
 - echo "Building toolkit using cmake"
 - cmake .
 - make VERBOSE=1

push-build:
  stage: build
  trigger: pd/cxxtk/cxx/ncbi-cxx-toolkit-core-conan

