image:
 name: ${CI_REGISTRY}/pd/do/images/base/production:latest
 entrypoint: ["/bin/bash", "-c"]

stages:
 - build
 - push-build

build:
 stage: build
 timeout: 5 hours
 script:
  - echo "Building toolkit using cmake"
  - ./cmake-configure --with-dll 2>&1 | tee config.log
  - cd CMake-GCC730-DebugDLL/build
  - DISTCC_VERBOSE=1 DISTCC_LOG=`pwd`/distcc.log  make VERBOSE=0 -j 8 2>&1 | tee build.log
 artifacts:
  paths:
   - config.log
   - build.log
   - distcc.log
  expire_in: never

push-build:
  stage: build
  trigger: pd/cxxtk/cxx/ncbi-cxx-toolkit-core-conan

