image:
 name: ${CI_REGISTRY}/pd/do/images/base/production:latest
 entrypoint: ["/bin/bash", "-c"]

stages:
 - build
 - push-build

build:
 stage: build
 timeout: 5 hours
 script:
  - echo "Testing distcc connection"
  - ping -c 3 distcc11
  - echo 'exit' |telnet  distcc11 3632
  - echo "Building toolkit using cmake"
  - ./cmake-configure --with-dll
  - cd CMake-GCC730-DebugDLL/build
  - make VERBOSE=0 -j 8

push-build:
  stage: build
  trigger: pd/cxxtk/cxx/ncbi-cxx-toolkit-core-conan

