image:
 name: ${CI_REGISTRY}/pd/do/images/base/production:latest
 entrypoint: ["/bin/bash", "-c"]

stages:
 - build
 - test

default:
  retry:
    max: 2
    when: runner_system_failure

build:
 stage: build
 timeout: 5 hours
 script:
  - export NCBI=/opt/ncbi/64
  - adduser toolkit
  - echo "Building toolkit using cmake"
  - ./cmake-configure --with-dll --with-projects=corelib 2>&1 | tee "${CI_PROJECT_DIR}/config.log"
  - cd CMake-GCC730-DebugDLL/build
  - DISTCC_VERBOSE=1 DISTCC_LOG="${CI_PROJECT_DIR}/distcc.log"  make VERBOSE=0 -j 8 2>&1 | tee "${CI_PROJECT_DIR}/build.log"
  - cd ../../
  - echo "Running tests"
  - chown -R toolkit CMake-GCC730-DebugDLL/
  - cd CMake-GCC730-DebugDLL/build
  - su toolkit -c "make check VERBOSE=1" 2>&1 | tee "${CI_PROJECT_DIR}/test.log" || true
  - cd ../..
 artifacts:
  paths:
   - config.log
   - build.log
   - distcc.log
   - test.log
   - CMake-GCC730-DebugDLL/check/
  when: always
  expire_in: never
 cache:
  paths:
   - build.log

test:
 stage: test
 timeout: 5 hours
 script:
  - pwd
  - ls
  - if false; then cd CMake-GCC730-DebugDLL/build ; fi
  - if false; then make check_r VERBOSE=1 2>&1 | tee test.log; fi
 artifacts:
  paths:
   - test.log
  expire_in: never
 cache:
  paths:
   - build.log
