image:
 name: ${CI_REGISTRY}/pd/do/images/base/production:latest
 entrypoint: ["/bin/bash", "-c"]

stages:
 - build
 - push-build

build:
 stage: build
 script:
  - echo "Building toolkit using cmake"
  - ./cmake-configure
  - cd CMake-GCC730-Debug/build
  - make VERBOSE=1

push-build:
  stage: build
  trigger: pd/cxxtk/cxx/ncbi-cxx-toolkit-core-conan

